#라이브러리 선언

In [4]:
# Pandas 패키지 불러오기
import pandas as pd
import numpy as np

# CSV 파일을 읽어 Data Frame 변수에 저장하기
customerData = pd.read_csv("../dataset/customerdata.csv")

In [5]:
groupKey = ["ITEM"]

In [6]:
groupKey = ["PRODUCT"] #영향력이 큼

In [12]:
sortKey = ["EMI","AVGPRICE"]

In [15]:
customerData.sort_values(by=sortKey, ascending=[True,False])

     CUSTID     AVGPRICE  EMI  DEVICECOUNT  PRODUCTAGE          CUSTTYPE
130  W13404  4296.873743    3            6    1.100000        Early-bird
0    A13566  4273.900000    3            6    1.679181  Big-Screen-lover
113  T11473  4165.700000    3            6    1.780674  Big-Screen-lover
40   H16326  3988.935304    3            6    0.900000        Early-bird
107  S17396  3895.200000    3            6    2.055707  Big-Screen-lover
..      ...          ...  ...          ...         ...               ...
86   Q16449  3048.308860    1            3    2.369758      Sleeping-dog
73   O13586  2980.229239    1            3    2.038603      Sleeping-dog
140  Y12458  2976.211190    1            3    2.199677      Sleeping-dog
47   I17056  2963.370122    1            3    2.139196      Sleeping-dog
68   N14862  2390.083736    1            6    1.000000        Early-bird

[150 rows x 6 columns]

In [16]:
sortKey= ["PRODUCTAGE"]

In [17]:
customerData.sort_values(sortKey, ignore_index=True)

     CUSTID     AVGPRICE  EMI  DEVICECOUNT  PRODUCTAGE          CUSTTYPE
0    J10809  3676.135627    3            6    0.800000        Early-bird
1    J16445  3041.848186    3            6    0.800000        Early-bird
2    D11795  2991.014703    2            6    0.800000        Early-bird
3    G19717  2873.102202    2            6    0.800000        Early-bird
4    P19679  3256.152962    2            6    0.800000        Early-bird
..      ...          ...  ...          ...         ...               ...
145  S14751  3137.800000    2            5    3.326340  Big-Screen-lover
146  G15439  3559.617754    2            4    3.345695      Sleeping-dog
147  G15736  3624.700000    2            5    3.367229  Big-Screen-lover
148  D13030  3227.855655    2            4    3.467370      Sleeping-dog
149  T11512  3428.518977    2            4    3.483573      Sleeping-dog

[150 rows x 6 columns]

In [22]:
groupKey =["EMI"]

In [24]:
customerData.groupby(["EMI"])["AVGPRICE"].mean()

EMI
1    3119.031810
2    3441.429664
3    3559.487188
Name: AVGPRICE, dtype: float64