In [12]:
import pandas as pd
from sqlalchemy import create_engine, types

# Oracle 데이터베이스 연결 설정
hostname = '192.168.110.112'
port = '1521'
database = 'orcl'
username = 'kopo'
password = 'kopo'

engine = create_engine(f'oracle://{username}:{password}@{hostname}:{port}/{database}', echo=True)

# 데이터프레임 로드
path = '../'
for root, dirs, files in os.walk(path):
    for file in files:
        if file.endswith('.csv') or file.endswith('.xlsx'):
            file_path = os.path.join(root, file)

            # CSV 파일 및 Excel 파일 읽기
            if file.endswith('.csv'):
                data = pd.read_csv(file_path)
            else:
                data = pd.read_excel(file_path)

            # 테이블 이름 설정
            tableName = file.split('.')[0]
            tableName = tableName.lower()

            # 데이터 유형 설정
            objectColumns = list(data.columns[data.dtypes == 'object'])
            typeDict={}
            maxLen = 100

            for i in range(0, len(objectColumns)):
                typeDict[objectColumns[i]] = types.VARCHAR(maxLen)

            # 데이터베이스에 데이터 적재
            data.to_sql(name=tableName, if_exists="replace", con=engine, dtype=typeDict, index=False)

# 연결 닫기
engine.dispose()

2023-04-28 19:03:29,372 INFO sqlalchemy.engine.Engine select sys_context( 'userenv', 'current_schema' ) from dual
2023-04-28 19:03:29,373 INFO sqlalchemy.engine.Engine [raw sql] {}
2023-04-28 19:03:29,379 INFO sqlalchemy.engine.Engine SELECT value FROM v$parameter WHERE name = 'compatible'
2023-04-28 19:03:29,379 INFO sqlalchemy.engine.Engine [raw sql] {}
2023-04-28 19:03:29,381 INFO sqlalchemy.engine.Engine select value from nls_session_parameters where parameter = 'NLS_NUMERIC_CHARACTERS'
2023-04-28 19:03:29,382 INFO sqlalchemy.engine.Engine [raw sql] {}
2023-04-28 19:03:29,384 INFO sqlalchemy.engine.Engine SELECT table_name FROM all_tables WHERE table_name = CAST(:name AS VARCHAR2(128)) AND owner = CAST(:schema_name AS VARCHAR2(128))
2023-04-28 19:03:29,385 INFO sqlalchemy.engine.Engine [generated in 0.00094s] {'name': 'CALSDATA2', 'schema_name': 'KOPO'}
2023-04-28 19:03:29,388 INFO sqlalchemy.engine.Engine SELECT table_name FROM all_tables WHERE table_name = CAST(:name AS VARCHAR2(128)) AND owner = CAST(:schema_name AS VARCHAR2(128))
2023-04-28 19:03:29,389 INFO sqlalchemy.engine.Engine [cached since 0.004972s ago] {'name': 'CALSDATA2', 'schema_name': 'KOPO'}
2023-04-28 19:03:29,391 INFO sqlalchemy.engine.Engine SELECT table_name FROM all_tables WHERE nvl(tablespace_name, 'no tablespace') NOT IN ('SYSTEM', 'SYSAUX') AND OWNER = :owner AND IOT_NAME IS NULL AND DURATION IS NULL
2023-04-28 19:03:29,392 INFO sqlalchemy.engine.Engine [generated in 0.00074s] {'owner': 'KOPO'}
2023-04-28 19:03:29,478 INFO sqlalchemy.engine.Engine SELECT table_name, compression, compress_for FROM ALL_TABLES WHERE table_name = CAST(:table_name AS VARCHAR(128)) AND owner = CAST(:owner AS VARCHAR(128))
2023-04-28 19:03:29,479 INFO sqlalchemy.engine.Engine [generated in 0.00073s] {'table_name': 'CALSDATA2', 'owner': 'KOPO'}
2023-04-28 19:03:29,481 INFO sqlalchemy.engine.Engine
            SELECT
                col.column_name,
                col.data_type,
                col.char_length,
                col.data_precision,
                col.data_scale,
                col.nullable,
                col.data_default,
                com.comments,
                col.virtual_column,
                                col.default_on_null,
                (
                    SELECT id.generation_type || ',' || id.IDENTITY_OPTIONS
                    FROM ALL_TAB_IDENTITY_COLS id
                    WHERE col.table_name = id.table_name
                    AND col.column_name = id.column_name
                    AND col.owner = id.owner
                ) AS identity_options
            FROM all_tab_cols col
            LEFT JOIN all_col_comments com
            ON col.table_name = com.table_name
            AND col.column_name = com.column_name
            AND col.owner = com.owner
            WHERE col.table_name = CAST(:table_name AS VARCHAR2(128))
            AND col.hidden_column = 'NO'
         AND col.owner = :owner  ORDER BY col.column_id
2023-04-28 19:03:29,481 INFO sqlalchemy.engine.Engine [generated in 0.00060s] {'table_name': 'CALSDATA2', 'owner': 'KOPO'}
2023-04-28 19:03:29,489 INFO sqlalchemy.engine.Engine SELECT
ac.constraint_name,
ac.constraint_type,
loc.column_name AS local_column,
rem.table_name AS remote_table,
rem.column_name AS remote_column,
rem.owner AS remote_owner,
loc.position as loc_pos,
rem.position as rem_pos,
ac.search_condition,
ac.delete_rule
FROM all_constraints ac,
all_cons_columns loc,
all_cons_columns rem
WHERE ac.table_name = CAST(:table_name AS VARCHAR2(128))
AND ac.constraint_type IN ('R','P', 'U', 'C')
AND ac.owner = CAST(:owner AS VARCHAR2(128))
AND ac.owner = loc.owner
AND ac.constraint_name = loc.constraint_name
AND ac.r_owner = rem.owner(+)
AND ac.r_constraint_name = rem.constraint_name(+)
AND (rem.position IS NULL or loc.position=rem.position)
ORDER BY ac.constraint_name, loc.position
2023-04-28 19:03:29,490 INFO sqlalchemy.engine.Engine [generated in 0.00112s] {'table_name': 'CALSDATA2', 'owner': 'KOPO'}
2023-04-28 19:03:29,503 INFO sqlalchemy.engine.Engine SELECT a.index_name, a.column_name,
b.index_type, b.uniqueness, b.compression, b.prefix_length
FROM ALL_IND_COLUMNS a,
ALL_INDEXES b
WHERE
a.index_name = b.index_name
AND a.table_owner = b.table_owner
AND a.table_name = b.table_name
AND a.table_name = CAST(:table_name AS VARCHAR(128))AND a.table_owner = :schema ORDER BY a.index_name, a.column_position
2023-04-28 19:03:29,504 INFO sqlalchemy.engine.Engine [generated in 0.00096s] {'table_name': 'CALSDATA2', 'schema': 'KOPO'}
2023-04-28 19:03:29,506 INFO sqlalchemy.engine.Engine SELECT a.index_name, a.column_name,
b.index_type, b.uniqueness, b.compression, b.prefix_length
FROM ALL_IND_COLUMNS a,
ALL_INDEXES b
WHERE
a.index_name = b.index_name
AND a.table_owner = b.table_owner
AND a.table_name = b.table_name
AND a.table_name = CAST(:table_name AS VARCHAR(128))AND a.table_owner = :schema ORDER BY a.index_name, a.column_position
2023-04-28 19:03:29,507 INFO sqlalchemy.engine.Engine [cached since 0.004465s ago] {'table_name': 'CALSDATA2', 'schema': 'KOPO'}
2023-04-28 19:03:29,509 INFO sqlalchemy.engine.Engine SELECT
ac.constraint_name,
ac.constraint_type,
loc.column_name AS local_column,
rem.table_name AS remote_table,
rem.column_name AS remote_column,
rem.owner AS remote_owner,
loc.position as loc_pos,
rem.position as rem_pos,
ac.search_condition,
ac.delete_rule
FROM all_constraints ac,
all_cons_columns loc,
all_cons_columns rem
WHERE ac.table_name = CAST(:table_name AS VARCHAR2(128))
AND ac.constraint_type IN ('R','P', 'U', 'C')
AND ac.owner = CAST(:owner AS VARCHAR2(128))
AND ac.owner = loc.owner
AND ac.constraint_name = loc.constraint_name
AND ac.r_owner = rem.owner(+)
AND ac.r_constraint_name = rem.constraint_name(+)
AND (rem.position IS NULL or loc.position=rem.position)
ORDER BY ac.constraint_name, loc.position
2023-04-28 19:03:29,509 INFO sqlalchemy.engine.Engine [cached since 0.02017s ago] {'table_name': 'CALSDATA2', 'owner': 'KOPO'}
2023-04-28 19:03:29,520 INFO sqlalchemy.engine.Engine
            SELECT comments
            FROM all_tab_comments
            WHERE table_name = CAST(:table_name AS VARCHAR(128))
            AND owner = CAST(:schema_name AS VARCHAR(128))

2023-04-28 19:03:29,521 INFO sqlalchemy.engine.Engine [generated in 0.00139s] {'table_name': 'CALSDATA2', 'schema_name': 'KOPO'}
2023-04-28 19:03:29,524 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-04-28 19:03:29,525 INFO sqlalchemy.engine.Engine
DROP TABLE calsdata2
2023-04-28 19:03:29,525 INFO sqlalchemy.engine.Engine [no key 0.00058s] {}
2023-04-28 19:03:29,548 INFO sqlalchemy.engine.Engine COMMIT
2023-04-28 19:03:29,554 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-04-28 19:03:29,557 INFO sqlalchemy.engine.Engine
CREATE TABLE calsdata2 (
	"기본단위 [mm]" VARCHAR(100 CHAR),
	"Unnamed: 1" VARCHAR(100 CHAR),
	"Unnamed: 2" VARCHAR(100 CHAR),
	"Unnamed: 3" VARCHAR(100 CHAR),
	"Unnamed: 4" VARCHAR(100 CHAR),
	"Unnamed: 5" VARCHAR(100 CHAR),
	"Unnamed: 6" VARCHAR(100 CHAR),
	"Unnamed: 7" VARCHAR(100 CHAR),
	"Unnamed: 8" VARCHAR(100 CHAR),
	"Unnamed: 9" VARCHAR(100 CHAR),
	"Unnamed: 10" VARCHAR(100 CHAR),
	"Unnamed: 11" VARCHAR(100 CHAR),
	"Unnamed: 12" VARCHAR(100 CHAR),
	"Unnamed: 13" VARCHAR(100 CHAR),
	"Unnamed: 14" VARCHAR(100 CHAR),
	"Unnamed: 15" VARCHAR(100 CHAR),
	"Unnamed: 16" VARCHAR(100 CHAR),
	"Unnamed: 17" VARCHAR(100 CHAR),
	"Unnamed: 18" VARCHAR(100 CHAR),
	"Unnamed: 19" FLOAT,
	"Unnamed: 20" VARCHAR(100 CHAR),
	"Unnamed: 21" FLOAT,
	"Unnamed: 22" VARCHAR(100 CHAR),
	"Unnamed: 23" FLOAT,
	"Unnamed: 24" VARCHAR(100 CHAR),
	"Unnamed: 25" VARCHAR(100 CHAR),
	"Unnamed: 26" VARCHAR(100 CHAR),
	"Unnamed: 27" VARCHAR(100 CHAR),
	"Unnamed: 28" VARCHAR(100 CHAR),
	"Unnamed: 29" VARCHAR(100 CHAR),
	"Unnamed: 30" VARCHAR(100 CHAR),
	"Unnamed: 31" VARCHAR(100 CHAR),
	"Unnamed: 32" VARCHAR(100 CHAR),
	"Unnamed: 33" VARCHAR(100 CHAR),
	"Unnamed: 34" VARCHAR(100 CHAR),
	"Unnamed: 35" VARCHAR(100 CHAR),
	"Unnamed: 36" VARCHAR(100 CHAR),
	"Unnamed: 37" VARCHAR(100 CHAR),
	"Unnamed: 38" VARCHAR(100 CHAR),
	"Unnamed: 39" VARCHAR(100 CHAR),
	"Unnamed: 40" VARCHAR(100 CHAR),
	"Unnamed: 41" VARCHAR(100 CHAR),
	"Unnamed: 42" VARCHAR(100 CHAR),
	"Unnamed: 43" VARCHAR(100 CHAR),
	"Unnamed: 44" VARCHAR(100 CHAR),
	"Unnamed: 45" VARCHAR(100 CHAR),
	"Unnamed: 46" VARCHAR(100 CHAR),
	"Unnamed: 47" VARCHAR(100 CHAR),
	"Unnamed: 48" VARCHAR(100 CHAR),
	"Unnamed: 49" VARCHAR(100 CHAR),
	"Unnamed: 50" VARCHAR(100 CHAR),
	"Unnamed: 51" VARCHAR(100 CHAR),
	"Unnamed: 52" VARCHAR(100 CHAR),
	"Unnamed: 53" VARCHAR(100 CHAR),
	"Unnamed: 54" VARCHAR(100 CHAR),
	"Unnamed: 55" VARCHAR(100 CHAR),
	"Unnamed: 56" VARCHAR(100 CHAR),
	"Unnamed: 57" VARCHAR(100 CHAR),
	"Unnamed: 58" VARCHAR(100 CHAR),
	"Unnamed: 59" VARCHAR(100 CHAR),
	"Unnamed: 60" VARCHAR(100 CHAR),
	"Unnamed: 61" VARCHAR(100 CHAR),
	"Unnamed: 62" VARCHAR(100 CHAR),
	"Unnamed: 63" VARCHAR(100 CHAR),
	"Unnamed: 64" VARCHAR(100 CHAR),
	"Unnamed: 65" VARCHAR(100 CHAR),
	"Unnamed: 66" VARCHAR(100 CHAR),
	"Unnamed: 67" VARCHAR(100 CHAR),
	"Unnamed: 68" VARCHAR(100 CHAR)
)


2023-04-28 19:03:29,558 INFO sqlalchemy.engine.Engine [no key 0.00127s] {}
2023-04-28 19:03:29,574 INFO sqlalchemy.engine.Engine COMMIT
2023-04-28 19:03:29,579 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-04-28 19:03:29,586 INFO sqlalchemy.engine.Engine INSERT INTO calsdata2 ("기본단위 [mm]", "Unnamed: 1", "Unnamed: 2", "Unnamed: 3", "Unnamed: 4", "Unnamed: 5", "Unnamed: 6", "Unnamed: 7", "Unnamed: 8", "Unnamed: 9", "Unnamed: 10", "Unnamed: 11", "Unnamed: 12", "Unnamed: 13", "Unnamed: 14", "Unnamed: 15", "Unnamed: 16", "Unnamed: 17", "Unnamed: 18", "Unnamed: 19", "Unnamed: 20", "Unnamed: 21", "Unnamed: 22", "Unnamed: 23", "Unnamed: 24", "Unnamed: 25", "Unnamed: 26", "Unnamed: 27", "Unnamed: 28", "Unnamed: 29", "Unnamed: 30", "Unnamed: 31", "Unnamed: 32", "Unnamed: 33", "Unnamed: 34", "Unnamed: 35", "Unnamed: 36", "Unnamed: 37", "Unnamed: 38", "Unnamed: 39", "Unnamed: 40", "Unnamed: 41", "Unnamed: 42", "Unnamed: 43", "Unnamed: 44", "Unnamed: 45", "Unnamed: 46", "Unnamed: 47", "Unnamed: 48", "Unnamed: 49", "Unnamed: 50", "Unnamed: 51", "Unnamed: 52", "Unnamed: 53", "Unnamed: 54", "Unnamed: 55", "Unnamed: 56", "Unnamed: 57", "Unnamed: 58", "Unnamed: 59", "Unnamed: 60", "Unnamed: 61", "Unnamed: 62", "Unnamed: 63", "Unnamed: 64", "Unnamed: 65", "Unnamed: 66", "Unnamed: 67", "Unnamed: 68") VALUES (:"기본단위 [mm]", :"Unnamed: 1", :"Unnamed: 2", :"Unnamed: 3", :"Unnamed: 4", :"Unnamed: 5", :"Unnamed: 6", :"Unnamed: 7", :"Unnamed: 8", :"Unnamed: 9", :"Unnamed: 10", :"Unnamed: 11", :"Unnamed: 12", :"Unnamed: 13", :"Unnamed: 14", :"Unnamed: 15", :"Unnamed: 16", :"Unnamed: 17", :"Unnamed: 18", :"Unnamed: 19", :"Unnamed: 20", :"Unnamed: 21", :"Unnamed: 22", :"Unnamed: 23", :"Unnamed: 24", :"Unnamed: 25", :"Unnamed: 26", :"Unnamed: 27", :"Unnamed: 28", :"Unnamed: 29", :"Unnamed: 30", :"Unnamed: 31", :"Unnamed: 32", :"Unnamed: 33", :"Unnamed: 34", :"Unnamed: 35", :"Unnamed: 36", :"Unnamed: 37", :"Unnamed: 38", :"Unnamed: 39", :"Unnamed: 40", :"Unnamed: 41", :"Unnamed: 42", :"Unnamed: 43", :"Unnamed: 44", :"Unnamed: 45", :"Unnamed: 46", :"Unnamed: 47", :"Unnamed: 48", :"Unnamed: 49", :"Unnamed: 50", :"Unnamed: 51", :"Unnamed: 52", :"Unnamed: 53", :"Unnamed: 54", :"Unnamed: 55", :"Unnamed: 56", :"Unnamed: 57", :"Unnamed: 58", :"Unnamed: 59", :"Unnamed: 60", :"Unnamed: 61", :"Unnamed: 62", :"Unnamed: 63", :"Unnamed: 64", :"Unnamed: 65", :"Unnamed: 66", :"Unnamed: 67", :"Unnamed: 68")

TypeError: expecting string or bytes object